# Generated by Django 5.2 on 2026-05-03 07:15

import common.storage.upload_paths
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='star', max_length=50, verbose_name='Иконка')),
                ('required_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Требуемый рейтинг')),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Опыт (XP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['required_rating'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_joined', 'Присоединился к проекту'), ('project_left', 'Покинул проект'), ('task_assigned', 'Новое задание'), ('task_completed', 'Задача выполнена'), ('photo_uploaded', 'Фото загружено'), ('achievement_unlocked', 'Достижение разблокировано')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push уведомление'), ('both', 'Email + Push')], default='push', max_length=10, verbose_name='Тип рассылки')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('filter_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('filter_rating_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мин. рейтинг')),
                ('filter_rating_max', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Макс. рейтинг')),
                ('filter_active_days', models.IntegerField(default=30, help_text='Активные за последние N дней', verbose_name='Активность (дни)')),
                ('filter_role', models.CharField(choices=[('all', 'Все'), ('volunteer', 'Волонтёры'), ('organizer', 'Организаторы')], default='all', max_length=20)),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='Доставлено')),
                ('opened_count', models.IntegerField(default=0, verbose_name='Открыто')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='Кликнуто')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Массовая рассылка',
                'verbose_name_plural': 'Массовые рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('chat_type', models.CharField(choices=[('project', 'Чат проекта'), ('direct', 'Личный чат'), ('group', 'Группа')], db_index=True, default='project', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('last_read_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее прочтение')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('project_start', 'Начало проекта'), ('project_end', 'Завершение проекта'), ('task_deadline', 'Дедлайн задачи'), ('meeting', 'Встреча'), ('reminder', 'Напоминание'), ('custom', 'Свое событие')], db_index=True, default='custom', max_length=20)),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('visibility', models.CharField(choices=[('public', 'Публичное'), ('private', 'Приватное'), ('project', 'Только участники проекта')], default='public', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('reminder_minutes', models.IntegerField(blank=True, help_text='За сколько минут напомнить (15, 30, 60, 1440)', null=True)),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Широта места проведения', max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Долгота места проведения', max_digits=9, verbose_name='Долгота')),
                ('radius', models.IntegerField(choices=[(100, '100 метров'), (250, '250 метров'), (500, '500 метров'), (1000, '1 километр'), (2000, '2 километра')], default=500, help_text='Радиус зоны уведомления в метрах', verbose_name='Радиус')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='Сработало')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время срабатывания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Геолокационное напоминание',
                'verbose_name_plural': 'Геолокационные напоминания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/images/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/', verbose_name='Файл')),
                ('is_delivered', models.BooleanField(db_index=True, default=False, verbose_name='Доставлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено в')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Отправлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('opened', 'Открыто'), ('clicked', 'Кликнуто'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Получатель уведомления',
                'verbose_name_plural': 'Получатели уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('welcome', '🎉 Приветствие'), ('reminder', '⏰ Напоминание'), ('thanks', '🏆 Благодарность'), ('announcement', '📢 Объявление'), ('custom', '✨ Свой шаблон')], default='custom', max_length=20, verbose_name='Тип')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание деятельности')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Контактное лицо')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('notes', models.TextField(blank=True, verbose_name='Планируемые проекты')),
            ],
            options={
                'verbose_name': 'Заявка организатора',
                'verbose_name_plural': 'Заявки организаторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='Закреплено')),
            ],
            options={
                'verbose_name': 'Закрепленное сообщение',
                'verbose_name_plural': 'Закрепленные сообщения',
                'ordering': ['-pinned_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В обработке'), ('resolved', 'Решен'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('ai_chat', 'AI Чат'), ('manual', 'Ручное создание'), ('email', 'Email')], default='ai_chat', max_length=20, verbose_name='Источник')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решен')),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustFactorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='Изменение TF')),
                ('reason', models.CharField(choices=[('project_leave', 'Выход из проекта'), ('task_decline', 'Отклонение задачи'), ('photo_rating_5', 'Оценка фотоотчета: 5 звезд'), ('photo_rating_4', 'Оценка фотоотчета: 4 звезды'), ('photo_rating_3', 'Оценка фотоотчета: 3 звезды'), ('photo_rating_1_2', 'Оценка фотоотчета: 1-2 звезды'), ('photo_rejected', 'Отклонение фотоотчета организатором'), ('daily_penalty', 'Штраф за пропуск задания'), ('bonus_consecutive_tasks', 'Бонус: 5 заданий подряд'), ('bonus_consecutive_photos', 'Бонус: 3 фотоотчета на 5 звезд'), ('manual', 'Ручное изменение')], max_length=100, verbose_name='Причина')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип объекта')),
                ('related_object_id', models.IntegerField(default=0, verbose_name='ID объекта')),
                ('old_value', models.IntegerField(verbose_name='Старое значение TF')),
                ('new_value', models.IntegerField(verbose_name='Новое значение TF')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'История TrustFactor',
                'verbose_name_plural': 'История TrustFactor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_type', models.CharField(choices=[('text', 'печатает...'), ('image', 'отправляет фото...'), ('video', 'отправляет видео...'), ('file', 'отправляет файл...')], default='text', max_length=20, verbose_name='Тип действия')),
                ('started_at', models.DateTimeField(auto_now=True, verbose_name='Начало')),
            ],
            options={
                'verbose_name': 'Статус печати',
                'verbose_name_plural': 'Статусы печати',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фильтра')),
                ('filter_type', models.CharField(choices=[('users', 'Пользователи'), ('projects', 'Проекты'), ('tasks', 'Задачи')], max_length=20, verbose_name='Тип')),
                ('filters', models.JSONField(verbose_name='Параметры фильтра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сохраненный фильтр',
                'verbose_name_plural': 'Сохраненные фильтры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('telegram_link', 'Привязка Telegram'), ('email_verification', 'Подтверждение Email')], db_index=True, max_length=20, verbose_name='Тип верификации')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='Код')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Только для email_verification', max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
            ],
            options={
                'verbose_name': 'Код верификации',
                'verbose_name_plural': 'Коды верификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedbacksession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия обратной связи', 'verbose_name_plural': 'Сессии обратной связи'},
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerproject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текстовое сообщение'), ('photo', 'Фотоотчет'), ('system', 'Системное сообщение')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to='api.photo'),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_before_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='organizer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='volunteer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_telegram',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=common.storage.upload_paths.project_cover_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='gis2_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на 2ГИС'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='volunteer_type',
            field=models.CharField(choices=[('social', 'Социальная помощь'), ('environmental', 'Экологические проекты'), ('cultural', 'Культурные и развлекательные мероприятия')], db_index=True, default='environmental', max_length=20, verbose_name='Тип волонтерства'),
        ),
        migrations.AddField(
            model_name='task',
            name='decline_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='consecutive_5star_photos',
            field=models.IntegerField(default=0, verbose_name='Подряд фотоотчетов на 5 звезд'),
        ),
        migrations.AddField(
            model_name='user',
            name='consecutive_completed_tasks',
            field=models.IntegerField(default=0, verbose_name='Подряд выполненных заданий'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_rating_counted',
            field=models.BooleanField(default=True, verbose_name='Начальный рейтинг учтен'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_task_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего выполненного задания'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_photos/', verbose_name='Фото 3х4'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_source',
            field=models.CharField(blank=True, choices=[('mobile_app', 'Mobile App'), ('telegram_bot', 'Telegram Bot'), ('telegram', 'Telegram (legacy)'), ('web_portal', 'Web Portal'), ('both', 'Mobile + Telegram')], default='mobile_app', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_factor',
            field=models.IntegerField(db_index=True, default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Trust Factor'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_history',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='api.project'),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('under_review', 'На проверке'), ('revision', 'На доработке'), ('completed', 'Выполнено'), ('failed', 'Отклонено'), ('closed', 'Закрыто'), ('archived', 'В архиве')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=common.storage.upload_paths.task_image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(750)]),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='device_token_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='device_token_token_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['last_used_at'], name='device_token_last_used_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['session', 'timestamp'], name='feedback_msg_session_time_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['is_spam'], name='feedback_msg_spam_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksession',
            index=models.Index(fields=['project', 'is_active'], name='feedback_session_project_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'uploaded_at'], name='photo_status_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['moderated_at'], name='photo_moderated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['volunteer', 'status'], name='photo_volunteer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['project', 'status'], name='photo_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_deleted'], name='project_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator', 'is_deleted'], name='project_creator_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at', 'status'], name='project_created_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'status'], name='project_city_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='project_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'project'], name='task_status_project_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline_date'], name='task_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_approved'], name='user_role_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_organizer'], name='user_is_organizer_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organizer_status', 'date_joined'], name='user_org_status_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerproject',
            index=models.Index(fields=['is_active', 'joined_at'], name='vol_proj_active_joined_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='photo_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'volunteer'), name='unique_task_volunteer'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='task_assignment_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 750)), name='user_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('trust_factor__gte', 0), ('trust_factor__lte', 30)), name='user_trust_factor_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='user_average_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='volunteerproject',
            constraint=models.UniqueConstraint(fields=('volunteer', 'project'), name='unique_volunteer_project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='api.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='event',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='geofencereminder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to='api.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='geofencereminder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to='api.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='geofencereminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.bulknotification'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notificationtemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='organizerapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_application', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='api.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='api.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='pinnedmessage',
            name='pinned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Закрепил'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='trustfactorhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_factor_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='api.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_in_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersearchfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'created_at'], name='activity_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['type', 'created_at'], name='activity_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_type', 'is_active'], name='chat_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['project', 'is_active'], name='chat_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['chat', 'user'], name='chat_member_chat_user_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['user', 'notifications_enabled'], name='chat_member_user_notif_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', 'start_date'], name='event_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'start_date'], name='event_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'start_date'], name='event_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_deleted', 'start_date'], name='event_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencereminder',
            index=models.Index(fields=['user', 'is_active'], name='geofence_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencereminder',
            index=models.Index(fields=['project', 'is_active'], name='geofence_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencereminder',
            index=models.Index(fields=['event', 'is_active'], name='geofence_event_active_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencereminder',
            index=models.Index(fields=['is_active', 'is_triggered'], name='geofence_active_triggered_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='message_chat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='message_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read'], name='message_chat_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', 'created_at'], name='message_deleted_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['notification', 'status'], name='notif_recip_notif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'status'], name='notif_recip_user_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='bulknotification',
            index=models.Index(fields=['status', 'scheduled_at'], name='bulk_notif_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='bulknotification',
            index=models.Index(fields=['created_by', 'created_at'], name='bulk_notif_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerapplication',
            index=models.Index(fields=['status'], name='org_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerapplication',
            index=models.Index(fields=['created_at'], name='org_app_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pinnedmessage',
            index=models.Index(fields=['chat', 'pinned_at'], name='pinned_msg_chat_pinned_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinnedmessage',
            unique_together={('chat', 'message')},
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='support_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trustfactorhistory',
            index=models.Index(fields=['user', '-created_at'], name='tf_history_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='typingstatus',
            index=models.Index(fields=['chat', 'started_at'], name='typing_chat_started_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingstatus',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'unlocked_at'], name='user_ach_user_unlocked_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='usersearchfilter',
            index=models.Index(fields=['user', 'filter_type'], name='search_filter_user_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersearchfilter',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['verification_type', 'code', 'is_used'], name='verify_type_code_used_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'verification_type', 'is_used'], name='verify_user_type_used_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'is_used'], name='verify_email_used_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='verify_expires_idx'),
        ),
    ]
