# Generated by Django migration (choices + help_text for VerificationCode)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement_activity_bulknotification_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_type',
            field=models.CharField(
                choices=[
                    ('telegram_link', 'Привязка Telegram'),
                    ('email_verification', 'Подтверждение Email'),
                    ('password_reset', 'Сброс пароля'),
                ],
                db_index=True,
                max_length=20,
                verbose_name='Тип верификации',
            ),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text='Обязателен для подтверждения email и сброса пароля',
                null=True,
                verbose_name='Email',
            ),
        ),
    ]
