# Generated by Django 5.2 on 2026-05-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_verificationcode_password_reset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Кого заблокировали')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто заблокировал')),
            ],
            options={
                'verbose_name': 'Блокировка',
                'verbose_name_plural': 'Блокировки',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('user_profile', 'Профиль пользователя'), ('chat_message', 'Сообщение в чате'), ('photo_report', 'Фотоотчет'), ('project', 'Проект')], max_length=50, verbose_name='Тип контента')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID контента')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('reviewed', 'Рассмотрено'), ('resolved', 'Решено (Приняты меры)'), ('dismissed', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='На кого пожаловались')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'), models.Index(fields=['content_type', 'content_id'], name='api_report_content_97dd6c_idx')],
            },
        ),
    ]
