# Generated by Django 5.2 on 2025-10-23 20:49

from django.db import migrations, models
from common.storage.upload_paths import task_image_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=task_image_upload_path),
        ),
    ]
