# Generated by Django 5.2 on 2025-10-25 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0017_add_deleted_at_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push уведомление'), ('both', 'Email + Push')], default='push', max_length=10, verbose_name='Тип рассылки')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('filter_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('filter_rating_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мин. рейтинг')),
                ('filter_rating_max', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Макс. рейтинг')),
                ('filter_active_days', models.IntegerField(default=30, help_text='Активные за последние N дней', verbose_name='Активность (дни)')),
                ('filter_role', models.CharField(choices=[('all', 'Все'), ('volunteer', 'Волонтёры'), ('organizer', 'Организаторы')], default='all', max_length=20)),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='Доставлено')),
                ('opened_count', models.IntegerField(default=0, verbose_name='Открыто')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='Кликнуто')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Массовая рассылка',
                'verbose_name_plural': 'Массовые рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('opened', 'Открыто'), ('clicked', 'Кликнуто'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Получатель уведомления',
                'verbose_name_plural': 'Получатели уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('welcome', '🎉 Приветствие'), ('reminder', '⏰ Напоминание'), ('thanks', '🏆 Благодарность'), ('announcement', '📢 Объявление'), ('custom', '✨ Свой шаблон')], default='custom', max_length=20, verbose_name='Тип')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organizer_status', 'date_joined'], name='user_org_status_joined_idx'),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.bulknotification'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notificationtemplate', verbose_name='Шаблон'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['notification', 'status'], name='notif_recip_notif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'status'], name='notif_recip_user_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='bulknotification',
            index=models.Index(fields=['status', 'scheduled_at'], name='bulk_notif_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='bulknotification',
            index=models.Index(fields=['created_by', 'created_at'], name='bulk_notif_creator_idx'),
        ),
    ]
