# Generated by Django 5.2 on 2026-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_update_rating_constraint_to_750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gis2_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на 2ГИС'),
        ),
    ]
