# Generated by Django 5.2 on 2026-02-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_photo_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decline_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
