# Generated by Django 5.2 on 2026-02-24 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_task_decline_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('telegram_link', 'Привязка Telegram'), ('email_verification', 'Подтверждение Email')], db_index=True, max_length=20, verbose_name='Тип верификации')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='Код')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Только для email_verification', max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код верификации',
                'verbose_name_plural': 'Коды верификации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verification_type', 'code', 'is_used'], name='verify_type_code_used_idx'), models.Index(fields=['user', 'verification_type', 'is_used'], name='verify_user_type_used_idx'), models.Index(fields=['email', 'is_used'], name='verify_email_used_idx'), models.Index(fields=['expires_at'], name='verify_expires_idx')],
            },
        ),
    ]
