# Generated by Django 5.2 on 2026-03-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_recreate_chat_participants_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('under_review', 'На проверке'), ('completed', 'Выполнено'), ('failed', 'Отклонено'), ('closed', 'Закрыто'), ('archived', 'В архиве')], db_index=True, default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='Код')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения email',
                'verbose_name_plural': 'Коды подтверждения email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_used'], name='email_verify_email_used_idx'), models.Index(fields=['user', 'is_used'], name='email_verify_user_used_idx'), models.Index(fields=['expires_at'], name='email_verify_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код привязки Telegram',
                'verbose_name_plural': 'Коды привязки Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_used'], name='tg_link_code_code_used_idx'), models.Index(fields=['user', 'is_used'], name='tg_link_code_user_used_idx'), models.Index(fields=['expires_at'], name='tg_link_code_expires_idx')],
            },
        ),
    ]
