# Generated by Django 5.2 on 2026-03-23 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_recreate_chat_participants_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('under_review', 'На проверке'), ('completed', 'Выполнено'), ('failed', 'Отклонено'), ('closed', 'Закрыто'), ('archived', 'В архиве')], db_index=True, default='open', max_length=20),
        ),
    ]
