# Generated by Django 5.2 on 2026-03-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_activity_is_read_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
