# Generated by Django 5.2 on 2026-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
