# Generated by Django 5.2 on 2026-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_taskassignment_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('under_review', 'На проверке'), ('revision', 'На доработке'), ('completed', 'Выполнено'), ('failed', 'Отклонено'), ('closed', 'Закрыто'), ('archived', 'В архиве')], db_index=True, default='open', max_length=20),
        ),
    ]
