# Generated by Django 5.2 on 2025-10-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_project_city_alter_user_role_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerproject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='device_token_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status', 'uploaded_at'], name='photo_status_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['moderated_at'], name='photo_moderated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_deleted'], name='project_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator', 'is_deleted'], name='project_creator_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at', 'status'], name='project_created_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'project'], name='task_status_project_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline_date'], name='task_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_approved'], name='user_role_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_organizer'], name='user_is_organizer_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerproject',
            index=models.Index(fields=['is_active', 'joined_at'], name='vol_proj_active_joined_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicetoken',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform_token'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'volunteer'), name='unique_task_volunteer'),
        ),
        migrations.AddConstraint(
            model_name='volunteerproject',
            constraint=models.UniqueConstraint(fields=('volunteer', 'project'), name='unique_volunteer_project'),
        ),
    ]
