# Generated by Django 5.2 on 2025-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_devicetoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['session', 'timestamp'], name='feedback_msg_session_time_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['is_spam'], name='feedback_msg_spam_idx'),
        ),
    ]
