# Generated by Django 5.2 on 2025-10-02 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedbackmessage_is_flagged_feedbackmessage_is_spam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия обратной связи', 'verbose_name_plural': 'Сессии обратной связи'},
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текстовое сообщение'), ('photo', 'Фотоотчет'), ('system', 'Системное сообщение')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to='core.photo'),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='core.project'),
        ),
        migrations.AlterField(
            model_name='feedbacksession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='feedbacksession',
            index=models.Index(fields=['project', 'is_active'], name='feedback_session_project_idx'),
        ),
    ]
