# Generated by Django 5.2 on 2025-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_devicetoken_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='volunteer_type',
            field=models.CharField(choices=[('social', 'Социальная помощь'), ('environmental', 'Экологические проекты'), ('cultural', 'Культурные и развлекательные мероприятия')], db_index=True, default='environmental', max_length=20, verbose_name='Тип волонтерства'),
        ),
    ]
