# Generated by Django 5.2 on 2025-10-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_volunteer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_joined', 'Присоединился к проекту'), ('project_left', 'Покинул проект'), ('task_completed', 'Задача выполнена'), ('photo_uploaded', 'Фото загружено'), ('achievement_unlocked', 'Достижение разблокировано')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_user_created_idx'), models.Index(fields=['type', 'created_at'], name='activity_type_created_idx')],
            },
        ),
    ]
