# Generated by Django 5.2 on 2025-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizer_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=10),
        ),
    ]
