# Generated by Django 5.2 on 2025-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_organizer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='organizer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='volunteer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
