# Generated by Django 5.2 on 2025-10-23 20:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.task_image_upload_path),
        ),
    ]
