# Generated by Django 5.2 on 2025-10-25 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bulknotification_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фильтра')),
                ('filter_type', models.CharField(choices=[('users', 'Пользователи'), ('projects', 'Проекты'), ('tasks', 'Задачи')], max_length=20, verbose_name='Тип')),
                ('filters', models.JSONField(verbose_name='Параметры фильтра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный фильтр',
                'verbose_name_plural': 'Сохраненные фильтры',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'filter_type'], name='search_filter_user_type_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
