# Generated by Django 5.2 on 2025-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0019_usersearchfilter'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['volunteer', 'status'], name='photo_volunteer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['project', 'status'], name='photo_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'status'], name='project_city_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='project_start_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='photo_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='task_assignment_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 500)), name='user_rating_range'),
        ),
    ]
