# Generated by Django 5.2 on 2025-10-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_photo_photo_volunteer_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
