# Generated by Django 5.2 on 2025-10-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bulknotification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('project_start', 'Начало проекта'), ('project_end', 'Завершение проекта'), ('task_deadline', 'Дедлайн задачи'), ('meeting', 'Встреча'), ('reminder', 'Напоминание'), ('custom', 'Свое событие')], db_index=True, default='custom', max_length=20)),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('visibility', models.CharField(choices=[('public', 'Публичное'), ('private', 'Приватное'), ('project', 'Только участники проекта')], default='public', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('reminder_minutes', models.IntegerField(blank=True, help_text='За сколько минут напомнить (15, 30, 60, 1440)', null=True)),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('participants', models.ManyToManyField(blank=True, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.project', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['creator', 'start_date'], name='event_creator_date_idx'), models.Index(fields=['project', 'start_date'], name='event_project_date_idx'), models.Index(fields=['event_type', 'start_date'], name='event_type_date_idx'), models.Index(fields=['is_deleted', 'start_date'], name='event_deleted_date_idx')],
            },
        ),
    ]
