# Generated by Django 5.2 on 2025-10-28 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Широта места проведения', max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Долгота места проведения', max_digits=9, verbose_name='Долгота')),
                ('radius', models.IntegerField(choices=[(100, '100 метров'), (250, '250 метров'), (500, '500 метров'), (1000, '1 километр'), (2000, '2 километра')], default=500, help_text='Радиус зоны уведомления в метрах', verbose_name='Радиус')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='Сработало')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время срабатывания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to='core.event', verbose_name='Событие')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to='core.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Геолокационное напоминание',
                'verbose_name_plural': 'Геолокационные напоминания',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='geofence_user_active_idx'), models.Index(fields=['project', 'is_active'], name='geofence_project_active_idx'), models.Index(fields=['event', 'is_active'], name='geofence_event_active_idx'), models.Index(fields=['is_active', 'is_triggered'], name='geofence_active_triggered_idx')],
            },
        ),
    ]
