# Generated by Django 5.2 on 2025-10-30 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_update_max_rating_to_750'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлено в'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Доставлено'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('last_read_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее прочтение')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='core.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
                'indexes': [models.Index(fields=['chat', 'user'], name='chat_member_chat_user_idx'), models.Index(fields=['user', 'notifications_enabled'], name='chat_member_user_notif_idx')],
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='Закреплено')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='core.chat', verbose_name='Чат')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.message', verbose_name='Сообщение')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Закрепил')),
            ],
            options={
                'verbose_name': 'Закрепленное сообщение',
                'verbose_name_plural': 'Закрепленные сообщения',
                'ordering': ['-pinned_at'],
                'indexes': [models.Index(fields=['chat', 'pinned_at'], name='pinned_msg_chat_pinned_idx')],
                'unique_together': {('chat', 'message')},
            },
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_type', models.CharField(choices=[('text', 'печатает...'), ('image', 'отправляет фото...'), ('video', 'отправляет видео...'), ('file', 'отправляет файл...')], default='text', max_length=20, verbose_name='Тип действия')),
                ('started_at', models.DateTimeField(auto_now=True, verbose_name='Начало')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='core.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_in_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус печати',
                'verbose_name_plural': 'Статусы печати',
                'indexes': [models.Index(fields=['chat', 'started_at'], name='typing_chat_started_idx')],
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
