# Generated by Django 5.2 on 2025-11-09 20:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_organizerapplication'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_photo ADD COLUMN IF NOT EXISTS is_before_after boolean NOT NULL DEFAULT false",
                    reverse_sql="ALTER TABLE core_photo DROP COLUMN IF EXISTS is_before_after",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='photo',
                    name='is_before_after',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_telegram',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.project_cover_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_source',
            field=models.CharField(blank=True, choices=[('mobile_app', 'Mobile App'), ('telegram_bot', 'Telegram Bot'), ('telegram', 'Telegram (legacy)'), ('web_portal', 'Web Portal'), ('both', 'Mobile + Telegram')], default='mobile_app', max_length=20, null=True),
        ),
    ]
