# Generated by Django 5.2 on 2025-11-17 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_photo_is_before_after_project_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('project_joined', 'Присоединился к проекту'), ('project_left', 'Покинул проект'), ('task_assigned', 'Новое задание'), ('task_completed', 'Задача выполнена'), ('photo_uploaded', 'Фото загружено'), ('achievement_unlocked', 'Достижение разблокировано')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код привязки Telegram',
                'verbose_name_plural': 'Коды привязки Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_used'], name='tg_link_code_code_used_idx'), models.Index(fields=['user', 'is_used'], name='tg_link_code_user_used_idx'), models.Index(fields=['expires_at'], name='tg_link_code_expires_idx')],
            },
        ),
    ]
