# Generated by Django 5.2 on 2025-11-17 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
