# Generated by Django 5.2 on 2025-11-17 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fix_all_user_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_photos/', verbose_name='Фото 3х4'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_history',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
    ]
