# Generated by Django 5.2 on 2026-02-02 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_age_user_bio_user_gender_user_portfolio_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В обработке'), ('resolved', 'Решен'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('ai_chat', 'AI Чат'), ('manual', 'Ручное создание'), ('email', 'Email')], default='ai_chat', max_length=20, verbose_name='Источник')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='support_user_status_idx'), models.Index(fields=['status', 'created_at'], name='support_status_created_idx')],
            },
        ),
    ]
