# Generated by Django 5.2 on 2026-02-15 16:50

from django.db import migrations


def create_default_achievements(apps, schema_editor):
    """Создает базовые достижения для системы"""
    Achievement = apps.get_model('core', 'Achievement')
    
    default_achievements = [
        {
            'name': 'Новичок',
            'description': 'Выполните первое задание и получите благодарность от команды BirQadam.',
            'icon': 'mdi-star-outline',
            'required_rating': 0,
            'xp': 10,
        },
        {
            'name': 'Активный волонтёр',
            'description': 'Выполните 5 заданий и покажите свою активность в проектах.',
            'icon': 'mdi-account-check',
            'required_rating': 50,
            'xp': 25,
        },
        {
            'name': 'Фото эксперт',
            'description': 'Отправьте 10 успешных фотоотчётов и помогите проекту с визуальными материалами.',
            'icon': 'mdi-camera',
            'required_rating': 100,
            'xp': 50,
        },
        {
            'name': 'Командный игрок',
            'description': 'Примите участие в трёх проектах подряд без пропусков и задержек.',
            'icon': 'mdi-account-group',
            'required_rating': 150,
            'xp': 75,
        },
        {
            'name': 'Опытный волонтёр',
            'description': 'Достигните 250 рейтинга и покажите свой опыт в волонтёрской деятельности.',
            'icon': 'mdi-trophy',
            'required_rating': 250,
            'xp': 100,
        },
        {
            'name': 'Профессионал',
            'description': 'Достигните 400 рейтинга и станьте профессионалом в волонтёрской работе.',
            'icon': 'mdi-medal',
            'required_rating': 400,
            'xp': 200,
        },
        {
            'name': 'Мастер',
            'description': 'Достигните максимального уровня мастерства! Вы прошли долгий путь и заслужили этот титул.',
            'icon': 'mdi-trophy-award',
            'required_rating': 750,
            'xp': 500,
        },
    ]
    
    for achievement_data in default_achievements:
        # Проверяем, существует ли уже такое достижение
        if not Achievement.objects.filter(required_rating=achievement_data['required_rating']).exists():
            Achievement.objects.create(**achievement_data)


def reverse_create_default_achievements(apps, schema_editor):
    """Удаляет достижения, созданные миграцией"""
    Achievement = apps.get_model('core', 'Achievement')
    Achievement.objects.filter(
        required_rating__in=[0, 50, 100, 150, 250, 400, 750]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_supportticket'),
    ]

    operations = [
        migrations.RunPython(create_default_achievements, reverse_create_default_achievements),
    ]
