# Generated by Django 5.2 on 2026-02-15 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0038_create_default_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustFactorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='Изменение TF')),
                ('reason', models.CharField(choices=[('project_leave', 'Выход из проекта'), ('photo_rating_5', 'Оценка фотоотчета: 5 звезд'), ('photo_rating_4', 'Оценка фотоотчета: 4 звезды'), ('photo_rating_1_2', 'Оценка фотоотчета: 1-2 звезды'), ('daily_penalty', 'Штраф за пропуск задания'), ('bonus_consecutive_tasks', 'Бонус: 5 заданий подряд'), ('bonus_consecutive_photos', 'Бонус: 3 фотоотчета на 5 звезд'), ('manual', 'Ручное изменение')], max_length=100, verbose_name='Причина')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип объекта')),
                ('related_object_id', models.IntegerField(default=0, verbose_name='ID объекта')),
                ('old_value', models.IntegerField(verbose_name='Старое значение TF')),
                ('new_value', models.IntegerField(verbose_name='Новое значение TF')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'История TrustFactor',
                'verbose_name_plural': 'История TrustFactor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='consecutive_5star_photos',
            field=models.IntegerField(default=0, verbose_name='Подряд фотоотчетов на 5 звезд'),
        ),
        migrations.AddField(
            model_name='user',
            name='consecutive_completed_tasks',
            field=models.IntegerField(default=0, verbose_name='Подряд выполненных заданий'),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_rating_counted',
            field=models.BooleanField(default=True, verbose_name='Начальный рейтинг учтен'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_task_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего выполненного задания'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_factor',
            field=models.IntegerField(db_index=True, default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Trust Factor'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('trust_factor__gte', 0), ('trust_factor__lte', 30)), name='user_trust_factor_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='user_average_rating_range'),
        ),
        migrations.AddField(
            model_name='trustfactorhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_factor_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trustfactorhistory',
            index=models.Index(fields=['user', '-created_at'], name='tf_history_user_created_idx'),
        ),
    ]
