# Generated by Django 5.2 on 2026-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0040_alter_trustfactorhistory_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_rating_range',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 750)), name='user_rating_range'),
        ),
    ]
