# Generated by Django 5.2 on 2026-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_gis2_url_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustfactorhistory',
            name='reason',
            field=models.CharField(choices=[('project_leave', 'Выход из проекта'), ('task_decline', 'Отклонение задачи'), ('photo_rating_5', 'Оценка фотоотчета: 5 звезд'), ('photo_rating_4', 'Оценка фотоотчета: 4 звезды'), ('photo_rating_3', 'Оценка фотоотчета: 3 звезды'), ('photo_rating_1_2', 'Оценка фотоотчета: 1-2 звезды'), ('daily_penalty', 'Штраф за пропуск задания'), ('bonus_consecutive_tasks', 'Бонус: 5 заданий подряд'), ('bonus_consecutive_photos', 'Бонус: 3 фотоотчета на 5 звезд'), ('manual', 'Ручное изменение')], max_length=100, verbose_name='Причина'),
        ),
    ]
