# Generated by Django 5.1.3 on 2025-11-12 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=36, verbose_name='User ID (from cookie)')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('action', models.CharField(max_length=100, verbose_name='Event Action')),
                ('url', models.URLField(max_length=255, verbose_name='Page URL')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=36, verbose_name='User ID (from cookie)')),
                ('type', models.CharField(max_length=20, verbose_name='Visit Type')),
                ('url', models.URLField(max_length=255, verbose_name='Page URL')),
                ('referrer', models.URLField(blank=True, max_length=255, null=True, verbose_name='HTTP Referrer')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
