pipeline {
  agent { label 'deployment_1' }

  environment {
    // имя проекта для docker compose (опционально)
    COMPOSE_PROJECT_NAME = 'cleanup-almaty'
    // просто чтобы красиво вывести в конце
    APP_PORT = '8003'
  }

  stages {
    stage('Checkout') {
      steps {
        // если это multibranch — обычно достаточно checkout scm
        checkout scm
      }
    }

    stage('Prepare .env from Jenkins credentials') {
      steps {
        dir('BirQadamDjango') {
          // В Jenkins должен быть создан Secret file с ID: cleanup-almaty-env
          withCredentials([file(credentialsId: 'cleanup-almaty-env', variable: 'ENV_FILE')]) {
            sh '''
              echo "Using secret .env from Jenkins credentials..."
              cp "$ENV_FILE" .env || true
              ls -la .env
            '''
          }
        }
      }
    }


    stage('Prepare .env for front from Jenkins credentials') {
      steps {
        dir('BirQadamDjango') {
          // В Jenkins должен быть создан Secret file с ID: birqadam-front-env
          withCredentials([file(credentialsId: 'birqadam-front-env', variable: 'ENV_FILE')]) {
            sh '''
              echo "Using secret .env from Jenkins credentials..."
              cp "$ENV_FILE" ./frontend/.env || true
              ls -la .env
            '''
          }
        }
      }
    }

    stage('Deploy with Docker Compose') {
      steps {
        dir('BirQadamDjango') {
          // Если у тебя установлен docker-compose как бинарник,
          // замени `docker compose` на `docker-compose`
          sh '''
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
          '''
        }
      }
    }
  }

  post {
    success {
      echo "✅ Deployed successfully: http://your-server:${APP_PORT}"
    }
    failure {
      echo "❌ Deployment failed"
    }
  }
}
