services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: birqadam
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn birqadam_project.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8002:8000"
    volumes:
      - ../media:/app/media
      - ../staticfiles:/app/staticfiles
    env_file:
      - path: ../.env
        required: false
    depends_on:
      - redis

  celery:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: django_celery
    command: celery -A birqadam_project worker -l info
    env_file:
      - path: ../.env
        required: false
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ../portal_frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://cleanup.almau.edu.kz/
    container_name: birqadam_frontend
    ports:
      - "4172:4173"
